name: Python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
      
    - name: Install Chromium browser and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser=110.0.5481.77-0ubuntu0.18.04.1~snap1 chromium-chromedriver=110.0.5481.77-0ubuntu0.18.04.1~snap1
      
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      
    - name: Print Chromium browser version and Chromedriver version
      run: |
        chromium-browser --version
        chromedriver --version
      
    - name: Run the script
      run: |
        python ms_rewards_farmer.py
